name: Refresh data
on:
  push:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  refresh_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/cache@v2
      name: Cache dependencies
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create folders
      run: |
        ./reset_folders.sh >/dev/null
    - name: Pull iati-data repo
      run: |
        mkdir iati-data
        echo "START_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
    - name: Fetch URLs and metadata
      run: |
        python grab_urls.py
    - name: Fetch data
      run: |
        ./fetch_data.sh
        echo "." >> errors
        echo "END_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
    - name: Create initial metadata.json
      run: |
        echo "{\"created_at\": \"${{ env.START_TIMESTAMP }}\", \"updated_at\": \"${{ env.END_TIMESTAMP }}\"}" > metadata.json
    - name: Move files into place
      run: |
        mv metadata iati-data
        mv data iati-data
        cp metadata.json iati-data
        zip -r iati-data.zip iati-data
    - uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.DO_ACCESS_KEY}}
        secret_key: ${{ secrets.DO_SECRET_KEY }}
        space_name: ${{ secrets.DO_SPACE_NAME }}
        space_region: ${{ secrets.DO_SPACE_REGION }}
        source: iati-data.zip
#   - name: Push to gitlab
#     run: |
#       cd iati-data
#       git config --global user.name 'Code for IATI bot'
#       git config --global user.email '10231116-codeforIATIbot@users.noreply.gitlab.com'
#       git config core.autocrlf false
#       git add .
#       git commit --quiet --message='Update'
#       git push --quiet origin main
#       cd ..
#   - name: Adding token to .gist
#     run: |
#       echo "${{ secrets.GH_TOKEN }}" > ~/.gist
#       bundle exec gist -u efd190029713c6775c43962444dcb8df metadata.json
#   - name: Uploading errors to gist
#     run: |
#       bundle exec gist -u f117c9be138aa94c9762d57affc51a64 errors
    - name: Tidy up
      run: |
        rm -rf metadata.json errors iati-data
        ./reset_folders.sh >/dev/null
